import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DemoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className="absolute bottom-0 w-full">
          <div className="text-center mx-auto px-6 pt-10 pb-6">
            <span className="text-lg">
              ALL RIGHTS RESERVED © 2023 MAQUIS SCOTT Child
            </span>
          </div>
        </div>
      </body>
    </html>
  );
}
