import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="lg:h-[95vh] h-screen">
          {children}
          <footer className="sticky text-center align-middle">
            All rights reserved &copy; Maquis Scott
          </footer>
        </div>
      </body>
    </html>
  );
}
